name: flutter_chat_demo
description: This is the demo for chat app by Flutter
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: 3.0.0
  cached_network_image: ^3.2.3
  file_picker: ^5.2.5
  firebase_auth: ^3.3.7
  firebase_core: ^1.24.0
  firebase_core_web: ^1.7.3
  firebase_storage: ^10.3.11
  firebase_storage_web: ^3.3.9
  font_awesome_flutter: ^10.3.0
  google_fonts: ^4.0.0
  google_sign_in: ^5.2.4
  image_picker: ^0.8.6+1
  intl: 0.17.0
  json_path: ^0.4.2
  mime_type: 1.0.0
  page_transition: ^2.0.9
  rxdart: ^0.27.7
  shared_preferences: ^2.0.17
  sign_in_with_apple:
    git:
      url: https://github.com/asmengistu/dart_packages
      ref: ab18d53a80e0a4bb90f1ad84f37f1b408930f28d
      path: packages/sign_in_with_apple/sign_in_with_apple/
  timeago: ^3.3.0
  url_launcher: ^6.1.8

  cupertino_icons: ^1.0.5
  cloud_firestore: ^3.5.1
  fluttertoast: ^8.1.2
  #firebase_messaging: 9.1.3
  flutter_local_notifications: ^13.0.0
  photo_view: ^0.14.0
  provider: ^6.0.1
  flutter_launcher_icons: ^0.11.0
  google_maps_flutter: ^2.1.8
  auth_service:
    path: packages/auth_service
  email_validator: '^2.1.16'
  agora_rtc_engine: ^6.0.0
  permission_handler: ^10.2.0
  agora_uikit: ^1.1.0
  firebase_messaging: ^13.1.0
  flutter_ringtone_player: ^3.2.0
  # firebase_in_app_messaging: ^0.6.0+25
    

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "images/app_icon.png" 
  android: true
  ios: true
  # optionally, as transparency is not allowed on app store
  # remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - images/

