name: flutter_chat_demo
description: This is the demo for chat app by Flutter
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: 3.0.0
  cached_network_image: 3.1.0+1
  file_picker: 4.5.1
  firebase_auth: 3.2.0
  firebase_core: 1.12.0
  firebase_core_web: 1.5.4
  firebase_storage: 10.1.0
  firebase_storage_web: 3.2.8
  font_awesome_flutter: 10.1.0
  google_fonts: 2.2.0
  google_sign_in: 5.2.1
  image_picker: 0.8.4+4
  intl: 0.17.0
  json_path: 0.3.1
  mime_type: 1.0.0
  page_transition: 2.0.4
  rxdart: 0.26.0
  shared_preferences: 2.0.11
  sign_in_with_apple:
    git:
      url: https://github.com/asmengistu/dart_packages
      ref: ab18d53a80e0a4bb90f1ad84f37f1b408930f28d
      path: packages/sign_in_with_apple/sign_in_with_apple/
  timeago: 3.1.0
  url_launcher: 6.0.15

  cupertino_icons: ^0.1.3
  cloud_firestore:  2.0.0
  fluttertoast: 8.0.6
  #firebase_messaging: 9.1.3
  flutter_local_notifications: 5.0.0+4
  photo_view: 0.12.0
  provider: ^6.0.1
  flutter_launcher_icons: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "images/app_icon.png" 
  android: true
  ios: true
  # optionally, as transparency is not allowed on app store
  # remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - images/

